/* Database schema to keep the structure of entire database. */
CREATE TABLE animals (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  date_of_birth DATE NOT NULL,
  escape_attempts INT NOT NULL,
  neutered BOOLEAN NOT NULL,
  weight_kg DEC NOT NULL,
  PRIMARY KEY (id)
);

-- Add a column species of type string to your animals table.
ALTER TABLE
  animals
ADD
  species VARCHAR(100);

/* Create a table named owners with the following columns:
 id: integer (set it as autoincremented PRIMARY KEY)
 full_name: string
 age: integer */
CREATE TABLE owners (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  full_name VARCHAR(100) NOT NULL,
  age INT NOT NULL,
  PRIMARY KEY (id)
);

/* Create a table named species with the following columns:
 id: integer (set it as autoincremented PRIMARY KEY)
 name: string */
CREATE TABLE species (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

/* Modify animals table:
 Make sure that id is set as autoincremented PRIMARY KEY
 Remove column species
 Add column species_id which is a foreign key referencing species table
 Add column owner_id which is a foreign key referencing the owners table */
ALTER TABLE
  animals DROP species;

ALTER TABLE
  animals
ADD
  species_id INT;

ALTER TABLE
  animals
ADD
  CONSTRAINT fk_species FOREIGN KEY(species_id) REFERENCES species(id) ON DELETE CASCADE;

ALTER TABLE
  animals
ADD
  owner_id INT;

ALTER TABLE
  animals
ADD
  CONSTRAINT fk_owner FOREIGN KEY(owner_id) REFERENCES owners(id) ON DELETE CASCADE;

-- Other commands that I found helpful but aren't a part of the project:
-- Add constrain to escape_attempts field so that it can only contain positive values or zero
ALTER TABLE
  animals
ADD
  CONSTRAINT chk_escape_attempts CHECK (escape_attempts >= 0);

-- Add constrain to weight_kg field so that it can only contain positive values.
ALTER TABLE
  animals
ADD
  CONSTRAINT chk_weight_kg CHECK (weight_kg > 0);

-- Add constrain to date_of_birth field so that it can only contain previous dates from today.
ALTER TABLE
  animals
ADD
  CONSTRAINT chk_date_of_birth CHECK (date_of_birth < CURRENT_DATE);

-- Remove constraints.
ALTER TABLE
  animals DROP CONSTRAINT chk_escape_attempts;

ALTER TABLE
  animals DROP CONSTRAINT chk_weight_kg;

ALTER TABLE
  animals DROP CONSTRAINT chk_date_of_birth;

ALTER TABLE
  animals DROP CONSTRAINT fk_species;

ALTER TABLE
  animals DROP CONSTRAINT fk_owner;

-- Only to run in extreme cases.
DROP TABLE IF EXISTS animals;