/* Database schema to keep the structure of entire database. */
CREATE TABLE animals (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  date_of_birth DATE NOT NULL,
  escape_attempts INT NOT NULL,
  neutered BOOLEAN NOT NULL,
  weight_kg DEC NOT NULL,
  PRIMARY KEY (id)
);

-- Add a column species of type string to your animals table.
ALTER TABLE
  animals
ADD
  species VARCHAR(100);

-- Other commands that I found helpful but aren't a part of the project:
-- Add constrain to escape_attempts field so that it can only contain positive values or zero
ALTER TABLE
  animals
ADD
  CONSTRAINT check_escape_attempts CHECK (escape_attempts >= 0);

-- Add constrain to weight_kg field so that it can only contain positive values.
ALTER TABLE
  animals
ADD
  CONSTRAINT check_weight_kg CHECK (weight_kg > 0);

-- Add constrain to date_of_birth field so that it can only contain previous dates from today.
ALTER TABLE
  animals
ADD
  CONSTRAINT check_date_of_birth CHECK (date_of_birth < CURRENT_DATE);

-- Remove constraints.
ALTER TABLE
  animals DROP CONSTRAINT check_escape_attempts;

ALTER TABLE
  animals DROP CONSTRAINT check_weight_kg;

ALTER TABLE
  animals DROP CONSTRAINT check_date_of_birth;

-- Only to run in extreme cases.
DROP TABLE IF EXISTS animals;